version: '3'

services:
    db-headless:
        container_name: db-headless
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: wp_headless
            MYSQL_PASSWORD: wp_headless
            MYSQL_USER: wp_headless
        image: mariadb:10.3
        ports:
            - '3307:3306'

    wp-headless:
        build: .
        command: bash -c 'install_wordpress && apache2-foreground'
        container_name: wp-headless
        depends_on:
            - db-headless
        env_file: ./.env
        ports:
            - '8080:8080'
        user: www-data
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/migratedb_import.sh:/usr/local/bin/migratedb_import
            - ./docker/theroyalsheadlesswpstarter.wordpress.xml:/var/www/theroyalsheadlesswpstarter.wordpress.xml
            - ./docker/plugins:/var/www/plugins

    frontend:
        command: bash -c 'yarn && yarn start'
        container_name: frontend
        depends_on:
            - wp-headless
        expose:
            - '3000'
        image: node:10
        environment:
            GRAPHQL_ENDPOINT: http://wp-headless:8080/graphql
        ports:
            - '3000:3000'
        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app
